### ISSUE TITLE
RazorPay Integration Error

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Flask-Generate-Certificate#14]
### **To Reproduce**
1. Go to index page
2. Scroll down to pricing section
3. The very last line of each plan says Error Occurred.

### **Expected behavior**
RazorPay Payment Button should be there if implemented correctly.

**Comment by vigneshshettyin** [comment]
Hey Ashutosh Krishna! 

Instead of using the Razorpay payments button, I would suggest you create a mock of the payments procedure. ie when the user clicks on that button (payment button) a modal (https://getbootstrap.com/docs/4.0/components/modal/) should be invoked it should ask the user for the plan, card details, name, email, and phone. Then head over to Braintree (https://www.braintreepayments.com/) Create a sandbox refer to the documentation for setup procedures. Then pass the data collected to Braintree servers which in return will give you a JSON response to store the important parameters in the backend dashboard.

**Comment by ashutoshkrris** [comment]
I would like to work on it.

**Comment by vigneshshettyin** [comment]
Okay, I'll assign it to you.
