### ISSUE TITLE
Add virtual environment

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Flask-Generate-Certificate#67]
I think it should be added in the getting started steps to create a virtual env before installing requirements.txt

**Comment by APratham** [comment]
@arpit456jain It is recommended that you open only one issue at a time so that you leave out space for others to contribute as well. Also coming back to your issue, while documenting something, it is always best to keep things simple. 

That is why a virtual environment is not mentioned in the instructions. If you want to, you can create an environment. 

@vigneshshettyin What do you think

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain creating a virtual environment is recommended. But nowadays developers commonly use **Pycharm** for flask app development in which virtual environment gets created automatically so, there won't be an issue.  

I think it's better we add steps to create a virtual env in getting started.

@APratham, @shades-7, @rexdivakar What do you think?

**Comment by rexdivakar** [comment]
Guys please don't encourage folks working on non materialistic changes as this creates a very bad impression over the coding community also I don't - think Dev's wouldnt be such lame asking for docs for installing requirements. 

Please don't encourage these kinds of things !!

**Comment by vigneshshettyin** [comment]
Yup @rexdivakar your right.
