### ISSUE TITLE
Email and Password Validation

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Flask-Generate-Certificate#9]
User email must be validated by using a regular expression. A regular expression for emails can be found here (https://regexr.com/) Choose an apt one and implement it in the backend. Password also should meet the following conditions
1.) Password must be between 8 and 30 characters.
2.) Password must contain at least one uppercase, or capital, letter (ex: A, B, etc.).
3.) Password must contain at least one lowercase letter.
4.) Password must contain at least one numeric digit (ex: 0, 1, 2, 3, etc.)
5.) Password must contain at least one special character -for example, $, #, @, !,%,^,&,*,(,)
When these conditions are not followed apt flash messages must be invoked.

**Comment by ashutoshkrris** [comment]
I want to work on this issue. Could you please assign it to me?
Also please add the GSSOC label @vigneshshettyin

**Comment by vigneshshettyin** [comment]
> I want to work on this issue. Could you please assign it to me?
> Also please add the GSSOC label @vigneshshettyin

Okay.

**Comment by ashutoshkrris** [comment]
@vigneshshettyin 
Instead of flashing message which will reload the page, I have used AJAX to validate the email and password as per the conditions mentioned above. The use of AJAX Requests makes it more user-friendly.
I have attached the demo. Please check and let me know if it's okay.
https://user-images.githubusercontent.com/47353498/110594333-ab169100-81a2-11eb-92a6-9b0567423f0e.mp4
